apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eliasafabargel/backend-calendar:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: mongodb://mongo-service:27017/pdf-calendar